const itemData = [
  {
    name: "howday",
    account: "48",
    category: "ffff",
    fromDate: "2021-12-5",
    toDate: "holo",
    fromFax: "12",
    ToFax: " -",
    Fax: "22.000",
    id: 1,
  },
  {
    name: "sanadd",
    account: "45",
    category: "DDDD",
    fromDate: "2019-10-5",
    toDate: "kpiloh",
    fromFax: "20",
    ToFax: " -",
    Fax: "100.000",
    id: 2,
  },
  {
    name: "foodid",
    account: "95",
    category: "AAAA",
    fromDate: "2018-11-15",
    toDate: "Jaiswal",
    fromFax: "11",
    ToFax: " -",
    Fax: "56.000",
    id: 3,
  },
  {
    name: "Vimalgolp",
    account: "15",
    category: "BBBB",
    fromDate: "1996-12-5",
    toDate: "Baiswal",
    fromFax: "10",
    ToFax: " -",
    Fax: "23.000",
    id: 4,
  },
  {
    name: "Babbel",
    account: "65",
    category: "OOOO",
    fromDate: "2015-12-9",
    toDate: "Pair",
    fromFax: "17",
    ToFax: " -",
    Fax: "15.000",
    id: 5,
  },
  {
    name: "Lopia",
    account: "40",
    category: "LLLL",
    fromDate: "2019-12-9",
    toDate: "Alopuyt",
    fromFax: "13",
    ToFax: " -",
    Fax: "87.000",
    id: 6,
  },
  {
    name: "Lorem",
    account: "45",
    category: "EEEE",
    fromDate: "2022-01-5",
    toDate: "Jaiswal",
    fromFax: "10",
    ToFax: " -",
    Fax: "45.000",
    id: 7,
  },
  {
    name: "Vimal",
    account: "65",
    category: "NNNN",
    fromDate: "2022-12-5",
    toDate: "Jaiswal",
    fromFax: "10",
    ToFax: " -",
    Fax: "35.000",
    id: 8,
  },
  {
    name: "Vimallop",
    account: "95",
    category: "NNNN",
    fromDate: "2022-12-5",
    toDate: "Jaiswal",
    fromFax: "10",
    ToFax: " -",
    Fax: "58.000",
    id: 9,
  },
];

export default itemData;
